name: Docker Image CI

on:
    push:
        branches: helldar

jobs:
    buildx:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php_version: [ 7.3, 7.4 ]
                arch: [ arm, arm64, amd64 ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Prepare
                id: prepare
                env:
                    PHP_VERSION: ${{ matrix.php_version }}
                    ARCH: ${{ matrix.arch }}
                run: |
                    DOCKER_IMAGE=helldar/laradock-workspace
                    DOCKER_PLATFORMS=linux/${ARCH}
                    VERSION=${PHP_VERSION}-${ARCH}
                    TAGS="--tag ${DOCKER_IMAGE}:${VERSION}"

                    echo ::set-output name=docker_image::${DOCKER_IMAGE}
                    echo ::set-output name=version::${VERSION}
                    echo ::set-output name=buildx_args::--platform ${DOCKER_PLATFORMS} \
                        --build-arg VERSION=${VERSION} \
                        --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
                        --build-arg VCS_REF=${GITHUB_SHA::8} \
                        ${TAGS} --file ./Dockerfile-${PHP_VERSION} ./
            -   name: Set up Docker Buildx
                uses: crazy-max/ghaction-docker-buildx@v3.3.0
            -   name: Docker Buildx (build)
                run: |
                    docker buildx build --output "type=image,push=false" ${{ steps.prepare.outputs.buildx_args }}
            -   name: Login to DockerHub
                if: success()
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKER_HUB_USER }}
                    password: ${{ secrets.DOCKER_HUB_PASSWORD }}
            -   name: Docker Buildx (push)
                if: success()
                run: |
                    docker buildx build --output "type=image,push=true" ${{ steps.prepare.outputs.buildx_args }}
            -   name: Inspect image
                if: always()
                run: |
                    docker buildx imagetools inspect ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }}
