name: Docker Image CI

on:
    push:
        branches: helldar
        tags:
            - v*

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Prepare
                id: prepare
                run: |
                    PREFIX=edge-
                    TAG=""

                    if [[ $GITHUB_REF == refs/tags/* ]]; then
                        PREFIX=latest-
                        TAG=${{ github.tag }}
                    fi

                    echo "PREFIX=${PREFIX}"
                    echo "TAG=${TAG}"
